/**
 * iRepoter
 * iReporter enables any/every citizen to bring any form of corruption to the notice of appropriate authorities and the general public. Users can also report on things that need government intervention around the community  Checkout the API on [Github](https://github.com/JamesMudidi/iReporterApi/tree/develop-v2) 
 *
 * OpenAPI spec version: 2.0
 * Contact: mudidi.jimmy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Pet
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object IRepoterApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 405 :  (Invalid input)
   * 
   * @param body Pet object that needs to be added to the store
   */
  def addPet(body: Pet): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/JamesMudidi/iRepoter/1.0.0", "/pet", "application/json")
      .withBody(body)
      .withErrorResponse[Unit](405)
      

}

